name: Build and Push to GHCR

on:
  push:
    tags:
      - t3-*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate valid repo name
        id: repo
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Generate image tag
        id: vars
        run: echo "tag=$(echo '${{ github.ref_name }}' | cut -d- -f2)" >> $GITHUB_OUTPUT

      - name: Generate create date
        id: create
        run: echo "create=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile
          build-args: |
            SGN_REPO=${{ github.repository }}
            SGN_BRANCH=${{ github.ref_name }}
            SGN_COMMIT=${{ github.sha }}
            DOCKER_TAG=${{ steps.vars.outputs.tag }}
            DOCKER_CREATED=${{ steps.create.outputs.create }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo }}:latest
            ghcr.io/${{ steps.repo.outputs.repo }}:${{ steps.vars.outputs.tag }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
          annotations: |
            manifest:org.opencontainers.image.description="Docker image automatically built from the GitHub repository ${{ github.repository }} [ref: ${{ github.ref_name }} sha: ${{ github.sha }}]."
          cache-from: type=gha
          cache-to: type=gha,mode=max